name: build

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2

      - name: Install dependencies
        run: |
          sudo apt install ffmpeg
          python -m pip install --upgrade pip
          pip install torch pytest

      - name: Set PYTHONPATH
        run: echo "::set-env name=PYTHONPATH::$GITHUB_WORKSPACE"

      - name: Run the tests
        run: pytest
